[package]
name = "serde-encrypted-value"
version = "0.3.0"
authors = ["Steven Fackler <sfackler@palantir.com>"]
license = "Apache-2.0"
description = "A Serde Deserializer wrapper which transparently decrypts encrypted values"
repository = "https://github.com/palantir/serde-encrypted-value"
documentation = "https://docs.rs/serde-encrypted-value/0.2.0/serde_encrypted_value"
readme = "README.md"

[dependencies]
base64 = "0.9"
openssl = "0.10"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

[dev-dependencies]
tempdir = "0.3"
